name: dev-terraform-workflow

on:
    push:
        branches:
            devlop
    workflow_dispatch:

jobs:
    dev-terraform:
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/reusable-workflow.yml
        with:
            environment: "dev"
        
